#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

$app = new Application();

foreach (require_once 'commands_list.php' as $command) {
    $app->add($command);
}

$app->run();
